### ISSUE TITLE
Access to scanning 3d data

### ISSUE THREAD

**Issue by manuel-kroeter** [cvg/visloc-iccv2021#1]
Hello,

thanks for providing this dataset. 
Is it possible to get also access to the 3d point / depth data of the mobile mapping?

**Comment by sarlinpe** [comment]
Hi Manuel,
The 3D lidar point clouds will be made publicly available for the full dataset release. This preview only contains the minimal modalities required for the ICCV localization challenge. Feel free to reach out by email if that can be useful for NavVis internals.

**Comment by manuel-kroeter** [comment]
Thanks, I contacted you by email.

**Comment by Alex-Beh** [comment]
Hi all, may I know the availability of 3D pointcloud data?

**Comment by sarlinpe** [comment]
We will release the point cloud data as part of the full release of the follow-up [LaMAR benchmark](https://lamar.ethz.ch/). This should happen soon.
